import { z } from 'zod';
import type { Hono } from 'hono';
import type { AppEnv } from '../app-context';
import { audit, jsonBody, parse, requireRestaurantRole } from '../app-context';
import { incidentsForEnv } from '../incidents/runtime';
import type { IncidentFactory } from '../incidents/service';

const managers=['buyer','approver','operator'] as const;const viewers=['buyer','approver','operator','action_owner','viewer'] as const;
export function registerIncidentRoutes(app:Hono<AppEnv>,factory:IncidentFactory=incidentsForEnv){
app.get('/v1/restaurants/:restaurantId/incidents',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),[...viewers]);return c.json({incidents:await factory(c.env).store.listIncidents(r)});});
app.post('/v1/restaurants/:restaurantId/incidents',async c=>{const r=c.req.param('restaurantId'),a=c.get('actor'),repo=c.get('repository');await requireRestaurantRole(repo,r,a,[...managers]);const input=parse(z.object({title:z.string().trim().min(3).max(300),category:z.string().trim().min(2).max(120),severity:z.enum(['low','medium','high','critical']),confidence:z.enum(['high','medium','low']),restricted:z.boolean().default(false),locationId:z.uuid().optional(),serviceMode:z.string().trim().max(80).optional(),menuItem:z.string().trim().max(200).optional(),daypart:z.string().trim().max(80).optional(),dateStart:z.string().optional(),dateEnd:z.string().optional(),rootCauseHypothesis:z.string().trim().max(2000).optional(),confirmedRootCause:z.string().trim().max(2000).optional(),ownerId:z.uuid().optional(),dueAt:z.iso.datetime().optional()}),await jsonBody(c));const incident=await factory(c.env).create(a,r,input);await audit(repo,a,{action:'incident.created',resourceType:'incident',resourceId:incident.id,restaurantId:r,metadata:{severity:incident.severity,restricted:incident.restricted}});return c.json({incident},201);});
app.get('/v1/restaurants/:restaurantId/incidents/:incidentId',async c=>{const r=c.req.param('restaurantId'),repo=c.get('repository'),actor=c.get('actor');const role=await requireRestaurantRole(repo,r,actor,[...viewers]);return c.json(await factory(c.env).detail(r,c.req.param('incidentId'),['buyer','approver','operator'].includes(role)));});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/signals',async c=>{const r=c.req.param('restaurantId'),a=c.get('actor'),repo=c.get('repository');await requireRestaurantRole(repo,r,a,[...managers]);const input=parse(z.object({signalType:z.enum(['review','listing_finding','manual']),signalId:z.string().trim().min(1).max(200),summary:z.string().trim().min(3).max(2000),category:z.string().trim().min(2).max(120),occurredAt:z.iso.datetime().optional(),confidence:z.enum(['high','medium','low']),confirmed:z.boolean().default(false)}),await jsonBody(c));const {confirmed,...signalInput}=input;const signal=await factory(c.env).addSignal(r,c.req.param('incidentId'),signalInput,confirmed);return c.json({signal},201);});
app.post('/v1/restaurants/:restaurantId/incidents/signals/:signalId/decision',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),[...managers]);const{decision}=parse(z.object({decision:z.enum(['confirmed','rejected'])}),await jsonBody(c));return c.json({signal:await factory(c.env).decideSignal(r,c.req.param('signalId'),decision)});});
app.get('/v1/restaurants/:restaurantId/incidents/grouping-suggestions',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),[...managers]);return c.json({suggestions:await factory(c.env).suggestGrouping(r)});});
app.patch('/v1/restaurants/:restaurantId/incidents/:incidentId',async c=>{const r=c.req.param('restaurantId'),a=c.get('actor'),repo=c.get('repository');await requireRestaurantRole(repo,r,a,[...managers]);const patch=parse(z.object({title:z.string().trim().min(3).max(300).optional(),category:z.string().trim().max(120).optional(),severity:z.enum(['low','medium','high','critical']).optional(),confidence:z.enum(['high','medium','low']).optional(),ownerId:z.uuid().optional(),dueAt:z.iso.datetime().optional(),rootCauseHypothesis:z.string().trim().max(2000).optional(),confirmedRootCause:z.string().trim().max(2000).optional(),escalationState:z.enum(['none','watch','escalated','contained']).optional(),status:z.enum(['open','investigating','action_required','verification_pending','resolved','dismissed','reopened','contained']).optional()}),await jsonBody(c));return c.json({incident:await factory(c.env).update(r,c.req.param('incidentId'),patch)});});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/actions',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),[...managers]);const input=parse(z.object({title:z.string().trim().min(2).max(300),description:z.string().trim().min(3).max(3000),assigneeId:z.uuid().optional(),approverId:z.uuid().optional(),dueAt:z.iso.datetime().optional(),dependencies:z.array(z.string().trim().max(200)).max(50).default([])}),await jsonBody(c));return c.json({action:await factory(c.env).addAction(r,c.req.param('incidentId'),input)},201);});
app.patch('/v1/restaurants/:restaurantId/incidents/actions/:actionId',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),[...managers]);const patch=parse(z.object({status:z.enum(['open','in_progress','completed','dismissed']).optional(),assigneeId:z.uuid().optional(),approverId:z.uuid().optional(),dueAt:z.iso.datetime().optional(),completionEvidence:z.string().trim().max(3000).optional()}),await jsonBody(c));return c.json({action:await factory(c.env).updateAction(r,c.req.param('actionId'),patch)});});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/evidence',async c=>{const r=c.req.param('restaurantId'),a=c.get('actor');await requireRestaurantRole(c.get('repository'),r,a,[...managers]);const input=parse(z.object({evidenceType:z.enum(['note','screenshot','document','metric','verification']),content:z.string().trim().min(3).max(5000),restricted:z.boolean().default(false)}),await jsonBody(c));return c.json({evidence:await factory(c.env).addEvidence(a,r,c.req.param('incidentId'),input)},201);});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/recovery',async c=>{const r=c.req.param('restaurantId'),a=c.get('actor');await requireRestaurantRole(c.get('repository'),r,a,['buyer','approver','operator']);const input=parse(z.object({contactStatus:z.enum(['not_requested','requested','completed','declined']),recoveryType:z.string().trim().max(200).optional(),compensationAuthority:z.enum(['none','approval_required','approved']),amountMinor:z.number().int().nonnegative().optional(),currency:z.string().trim().length(3).optional(),outcome:z.string().trim().max(2000).optional()}),await jsonBody(c));return c.json({recovery:await factory(c.env).addRecovery(a,r,c.req.param('incidentId'),input)},201);});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/verify',async c=>{const r=c.req.param('restaurantId'),a=c.get('actor');await requireRestaurantRole(c.get('repository'),r,a,['buyer','approver','operator']);const input=parse(z.object({result:z.enum(['verified_resolved','failed','inconclusive']),evidence:z.string().trim().min(3).max(5000)}),await jsonBody(c));return c.json({verification:await factory(c.env).verify(a,r,c.req.param('incidentId'),input.result,input.evidence)});});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/close',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),['buyer','approver']);const input=parse(z.object({mode:z.enum(['resolved','dismissed']),reason:z.string().trim().max(2000).optional()}),await jsonBody(c));return c.json({incident:await factory(c.env).close(r,c.req.param('incidentId'),input.mode,input.reason)});});
app.post('/v1/restaurants/:restaurantId/incidents/:incidentId/reopen',async c=>{const r=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),r,c.get('actor'),[...managers]);const{reason}=parse(z.object({reason:z.string().trim().min(3).max(2000)}),await jsonBody(c));return c.json({incident:await factory(c.env).reopen(r,c.req.param('incidentId'),reason)});});
}
