import { z } from 'zod';
import type { Hono } from 'hono';
import type { AppEnv } from '../app-context';
import { audit, jsonBody, parse, requireRestaurantRole } from '../app-context';
import { listingHealthForEnv } from '../listing-health/runtime';
import type { ListingHealthFactory } from '../listing-health/service';

const roles=['buyer','approver','operator'] as const;
const viewerRoles=['buyer','approver','operator','action_owner','viewer'] as const;
const facts=z.object({name:z.string().trim().max(160).optional(),address:z.string().trim().max(1000).optional(),latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional(),phone:z.string().trim().max(80).optional(),website:z.string().trim().max(1000).optional(),hours:z.record(z.string(),z.array(z.string())).optional(),holidayHours:z.record(z.string(),z.array(z.string())).optional(),serviceModes:z.array(z.string().trim().min(1).max(80)).max(30).optional(),orderingUrl:z.string().trim().max(1000).optional(),reservationUrl:z.string().trim().max(1000).optional(),menuUrl:z.string().trim().max(1000).optional(),categories:z.array(z.string().trim().min(1).max(120)).max(30).optional()});

export function registerListingHealthRoutes(app:Hono<AppEnv>,factory:ListingHealthFactory=listingHealthForEnv){
  app.post('/v1/restaurants/:restaurantId/listing-health/canonical',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,[...roles]);const input=parse(z.object({facts,confirmationSource:z.string().trim().min(3).max(500),effectiveAt:z.iso.datetime().optional(),expiresAt:z.iso.datetime().optional()}),await jsonBody(c));const version=await factory(c.env).createCanonical(actor,restaurantId,input.facts,input.confirmationSource,input.effectiveAt,input.expiresAt);await audit(repository,actor,{action:'listing.canonical_confirmed',resourceType:'business_fact_version',resourceId:version.id,restaurantId,metadata:{version:version.version}});return c.json({version},201);});
  app.get('/v1/restaurants/:restaurantId/listing-health/canonical',async c=>{const restaurantId=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),restaurantId,c.get('actor'),[...viewerRoles]);return c.json({versions:await factory(c.env).store.listFactVersions(restaurantId)});});
  app.post('/v1/restaurants/:restaurantId/listing-health/observations',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,[...roles]);const input=parse(z.object({source:z.enum(['manual','website','google','other']),sourceReference:z.string().trim().max(1000).optional(),facts,evidence:z.string().trim().max(2000).optional(),confidence:z.enum(['high','medium','low']),observedAt:z.iso.datetime()}),await jsonBody(c));const observation=await factory(c.env).observe(actor,restaurantId,input);await audit(repository,actor,{action:'listing.observation_recorded',resourceType:'listing_source_observation',resourceId:observation.id,restaurantId,metadata:{source:observation.source}});return c.json({observation},201);});
  app.get('/v1/restaurants/:restaurantId/listing-health/observations',async c=>{const restaurantId=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),restaurantId,c.get('actor'),[...viewerRoles]);return c.json({observations:await factory(c.env).store.listObservations(restaurantId)});});
  app.post('/v1/restaurants/:restaurantId/listing-health/compare',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,[...roles]);const{observationId}=parse(z.object({observationId:z.uuid()}),await jsonBody(c));const result=await factory(c.env).compare(restaurantId,observationId);await audit(repository,actor,{action:'listing.comparison_completed',resourceType:'listing_comparison_run',resourceId:result.run.id,restaurantId,metadata:{findingCount:result.run.findingCount,reused:result.reused}});return c.json(result);});
  app.get('/v1/restaurants/:restaurantId/listing-health/findings',async c=>{const restaurantId=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),restaurantId,c.get('actor'),[...viewerRoles]);let findings=await factory(c.env).store.listFindings(restaurantId);const status=c.req.query('status'),severity=c.req.query('severity');if(status)findings=findings.filter(f=>f.status===status);if(severity)findings=findings.filter(f=>f.severity===severity);return c.json({findings});});
  app.post('/v1/restaurants/:restaurantId/listing-health/findings/:findingId/decision',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,['buyer','approver']);const input=parse(z.object({decision:z.enum(['confirm','dismiss']),reason:z.string().trim().min(3).max(1000)}),await jsonBody(c));const finding=await factory(c.env).decideFinding(actor,restaurantId,c.req.param('findingId'),input.decision,input.reason);await audit(repository,actor,{action:'listing.finding_decided',resourceType:'listing_health_finding',resourceId:finding.id,restaurantId,metadata:{decision:input.decision}});return c.json({finding});});
  app.post('/v1/restaurants/:restaurantId/listing-health/findings/:findingId/assign',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,[...roles]);const input=parse(z.object({assignedTo:z.uuid(),dueAt:z.iso.datetime().optional()}),await jsonBody(c));return c.json({finding:await factory(c.env).assign(restaurantId,c.req.param('findingId'),input.assignedTo,input.dueAt)});});
  app.post('/v1/restaurants/:restaurantId/listing-health/findings/:findingId/corrections',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,[...roles]);const{evidence}=parse(z.object({evidence:z.string().trim().min(3).max(3000)}),await jsonBody(c));const attempt=await factory(c.env).recordCorrection(actor,restaurantId,c.req.param('findingId'),evidence);await audit(repository,actor,{action:'listing.correction_recorded',resourceType:'listing_correction_attempt',resourceId:attempt.id,restaurantId,metadata:{findingId:attempt.findingId}});return c.json({attempt},201);});
  app.post('/v1/restaurants/:restaurantId/listing-health/corrections/:attemptId/verify',async c=>{const restaurantId=c.req.param('restaurantId'),actor=c.get('actor'),repository=c.get('repository');await requireRestaurantRole(repository,restaurantId,actor,['buyer','approver','operator']);const input=parse(z.object({verified:z.boolean(),evidence:z.string().trim().min(3).max(3000)}),await jsonBody(c));const attempt=await factory(c.env).verifyCorrection(actor,restaurantId,c.req.param('attemptId'),input.verified,input.evidence);await audit(repository,actor,{action:'listing.correction_verified',resourceType:'listing_correction_attempt',resourceId:attempt.id,restaurantId,metadata:{verified:input.verified}});return c.json({attempt});});
  app.get('/v1/restaurants/:restaurantId/listing-health/snapshot',async c=>{const restaurantId=c.req.param('restaurantId');await requireRestaurantRole(c.get('repository'),restaurantId,c.get('actor'),[...viewerRoles]);return c.json({snapshot:await factory(c.env).snapshot(restaurantId)});});
}
