import{describe,expect,it}from'vitest';import type{Actor,Review,ReviewClassification}from'../src/domain/types';import{AutopilotService}from'../src/autopilot/service';import{MemoryAutopilotStore}from'../src/autopilot/store';
const actor:Actor={id:'11111111-1111-4111-8111-111111111111',platformRole:'user'},restaurantId='22222222-2222-4222-8222-222222222222';
const green:ReviewClassification={primaryCategory:'PRAISE',secondaryCategories:[],sentiment:'positive',risk:'green',confidence:'high',urgency:'normal',language:'English',serviceMode:'dine_in',safeFacts:[],unverifiedClaims:[],contextQuestions:[],recommendedDisposition:'reply_publicly',riskReason:'Low risk.',replyStrategyReason:'Thank customer.',policyFlags:[]};
const review=(classification:ReviewClassification=green):Pick<Review,'source'|'originalLanguage'|'classification'>=>({source:'google',originalLanguage:'English',classification});
async function setup(writesEnabled=true){const store=new MemoryAutopilotStore(),service=new AutopilotService(store,{enabled:true,writesEnabled,globalKill:false});const policy=await service.createPolicy(restaurantId,{level:3,allowedSources:['google'],allowedCategories:['PRAISE'],allowedLanguages:['English'],maxRisk:'green',voiceProfileId:'33333333-3333-4333-8333-333333333333',voiceProfileVersion:2,promptVersion:'p1',model:'m1',minimumShadowDecisions:2,minimumAgreementRate:1});return{store,service,policy}}
describe('Phase 8 controlled autopilot',()=>{
it('excludes amber, red, unknown, nonallowlisted sources and categories',async()=>{const{service,policy}=await setup();expect(service.evaluate(policy,review()).eligible).toBe(true);for(const risk of ['amber','red','unknown']as const){expect(service.evaluate(policy,review({...green,risk})).eligible).toBe(false)}expect(service.evaluate(policy,{...review(),source:'manual'}).eligible).toBe(false);expect(service.evaluate(policy,review({...green,primaryCategory:'STAFF'})).eligible).toBe(false)});
it('requires shadow evidence and written consent before activation',async()=>{const{service,policy}=await setup();await expect(service.activate(actor,restaurantId,policy.id,'Owner signed policy.')).rejects.toMatchObject({code:'shadow_gate_failed'});await service.shadow(restaurantId,policy.id,'r1',review(),'auto_publish');await service.shadow(restaurantId,policy.id,'r2',review(),'auto_publish');const active=await service.activate(actor,restaurantId,policy.id,'Owner signed policy.');expect(active.status).toBe('active');expect(active.consentEvidence).toBeTruthy()});
it('honors kill switches, write flags, revocation, and execution idempotency',async()=>{const{service,policy}=await setup();await service.shadow(restaurantId,policy.id,'r1',review(),'auto_publish');await service.shadow(restaurantId,policy.id,'r2',review(),'auto_publish');await service.activate(actor,restaurantId,policy.id,'Consent.');await service.setKillSwitch(actor,restaurantId,true,'Incident detected.');const blocked=await service.execute(restaurantId,policy.id,'r3',review(),'exec-123');expect(blocked.status).toBe('blocked');expect((await service.execute(restaurantId,policy.id,'r3',review(),'exec-123')).id).toBe(blocked.id);await service.setKillSwitch(actor,restaurantId,false,'Incident cleared.');const executed=await service.execute(restaurantId,policy.id,'r3',review(),'exec-456');expect(executed.status).toBe('executed');await service.revoke(restaurantId,policy.id);expect((await service.execute(restaurantId,policy.id,'r4',review(),'exec-789')).status).toBe('blocked')});
it('does not execute writes when the environment gate is disabled',async()=>{const{service,policy}=await setup(false);await service.shadow(restaurantId,policy.id,'r1',review(),'auto_publish');await service.shadow(restaurantId,policy.id,'r2',review(),'auto_publish');await service.activate(actor,restaurantId,policy.id,'Consent.');expect((await service.execute(restaurantId,policy.id,'r3',review(),'exec-disabled')).status).toBe('blocked')});
});
