import{describe,expect,it}from'vitest';import type{Actor}from'../src/domain/types';import{IncidentService}from'../src/incidents/service';import{MemoryIncidentStore}from'../src/incidents/store';
const actor:Actor={id:'11111111-1111-4111-8111-111111111111',platformRole:'user'},restaurantId='22222222-2222-4222-8222-222222222222';
async function setup(restricted=false){const store=new MemoryIncidentStore(),service=new IncidentService(store,{enabled:true});const incident=await service.create(actor,restaurantId,{title:'Repeated dinner delay',category:'SPEED',severity:'high',confidence:'medium',restricted});return{store,service,incident};}
describe('Phase 6 issue resolution',()=>{
it('groups multiple signals without losing originals or accepting suggestions silently',async()=>{const{service,incident}=await setup();const a=await service.addSignal(restaurantId,incident.id,{signalType:'review',signalId:'r1',summary:'Long dinner wait',category:'SPEED',confidence:'high'});await service.addSignal(restaurantId,incident.id,{signalType:'review',signalId:'r2',summary:'No update during wait',category:'SPEED',confidence:'medium'});expect((await service.suggestGrouping(restaurantId))[0]?.signalIds).toContain(a.id);expect(a.groupingStatus).toBe('suggested');expect((await service.decideSignal(restaurantId,a.id,'confirmed')).groupingStatus).toBe('confirmed');});
it('requires action evidence and verified resolution before closure',async()=>{const{service,incident}=await setup();const action=await service.addAction(restaurantId,incident.id,{title:'Check ticket times',description:'Review POS timings',dependencies:[]});await expect(service.updateAction(restaurantId,action.id,{status:'completed'})).rejects.toMatchObject({code:'evidence_required'});await service.updateAction(restaurantId,action.id,{status:'completed',completionEvidence:'POS report attached'});await expect(service.close(restaurantId,incident.id,'resolved')).rejects.toMatchObject({code:'verification_required'});await service.verify(actor,restaurantId,incident.id,'verified_resolved','Two-week check shows no recurrence.');expect((await service.close(restaurantId,incident.id,'resolved')).status).toBe('resolved');});
it('preserves history when reopened',async()=>{const{service,store,incident}=await setup();await service.close(restaurantId,incident.id,'dismissed','Duplicate operational report.');const reopened=await service.reopen(restaurantId,incident.id,'New review confirms recurrence.');expect(reopened.status).toBe('reopened');expect(await store.listEvidence(incident.id)).toHaveLength(1);});
it('restricts recovery to sensitive incidents and approved compensation',async()=>{const normal=await setup(false);await expect(normal.service.addRecovery(actor,restaurantId,normal.incident.id,{contactStatus:'requested',compensationAuthority:'none'})).rejects.toMatchObject({code:'restricted_incident_required'});const sensitive=await setup(true);await expect(sensitive.service.addRecovery(actor,restaurantId,sensitive.incident.id,{contactStatus:'completed',compensationAuthority:'approval_required',amountMinor:500,currency:'INR'})).rejects.toMatchObject({code:'compensation_not_approved'});const record=await sensitive.service.addRecovery(actor,restaurantId,sensitive.incident.id,{contactStatus:'completed',compensationAuthority:'approved',amountMinor:500,currency:'INR'});expect(record.amountMinor).toBe(500);});
});
