import{describe,expect,it}from'vitest';import type{Actor}from'../src/domain/types';import{OwnerIntelligenceService}from'../src/owner-intelligence/service';import{MemoryOwnerIntelligenceStore}from'../src/owner-intelligence/store';
const actor:Actor={id:'11111111-1111-4111-8111-111111111111',platformRole:'user'},restaurantId='22222222-2222-4222-8222-222222222222';
function service(deliveryEnabled=false){return new OwnerIntelligenceService(new MemoryOwnerIntelligenceStore(),{enabled:true,deliveryEnabled})}
const base={periodStart:'2026-07-06',periodEnd:'2026-07-12',metrics:{reviewVolume:{value:4,missing:false,unit:'count'as const,evidenceIds:['r1','r2']},publicationRate:{value:null,missing:true,unit:'ratio'as const,evidenceIds:[]}},wins:['Two positive food mentions.'],risks:['Small sample.'],pendingDecisions:['Confirm holiday hours.'],recommendations:[{title:'Check dinner ticket times',rationale:'Two reviews mention delay.',evidenceIds:['r1','r2']}]};
describe('Phase 7 owner intelligence',()=>{
it('distinguishes missing metrics from zero and produces a reproducible snapshot',async()=>{const s=service();const first=await s.generate(actor,restaurantId,base);expect(first.snapshot.metrics.publicationRate?.value).toBeNull();expect(first.snapshot.metrics.publicationRate?.missing).toBe(true);expect(first.report.smallSample).toBe(true);expect((await s.detail(restaurantId,first.report.id)).snapshot).toEqual(first.snapshot)});
it('enforces three evidence-backed actions and validation before approval',async()=>{const s=service();await expect(s.generate(actor,restaurantId,{...base,recommendations:[...base.recommendations,...base.recommendations,...base.recommendations,...base.recommendations]})).rejects.toMatchObject({code:'too_many_recommendations'});const created=await s.generate(actor,restaurantId,base);await expect(s.approve(actor,restaurantId,created.report.id)).rejects.toMatchObject({code:'invalid_state'});await s.validate(restaurantId,created.report.id);expect((await s.approve(actor,restaurantId,created.report.id)).status).toBe('approved')});
it('makes delivery idempotent and obeys channel preferences',async()=>{const s=service(true);const created=await s.generate(actor,restaurantId,base);await s.validate(restaurantId,created.report.id);await s.approve(actor,restaurantId,created.report.id);const blocked=await s.deliver(actor,restaurantId,created.report.id,'email','delivery-123');expect(blocked.status).toBe('blocked_by_preference');await s.preference({restaurantId,userId:actor.id,email:true,whatsappLink:false,inApp:true,updatedAt:new Date().toISOString()});const delivered=await s.deliver(actor,restaurantId,created.report.id,'email','delivery-456');expect(delivered.status).toBe('delivered');expect((await s.deliver(actor,restaurantId,created.report.id,'email','delivery-456')).id).toBe(delivered.id)});
it('tracks selected owner action to evidence-backed completion',async()=>{const s=service();const created=await s.generate(actor,restaurantId,base);const recommendation=created.recommendations[0]!;expect((await s.selectRecommendation(restaurantId,recommendation.id)).status).toBe('selected');await expect(s.completeRecommendation(restaurantId,recommendation.id,'')).rejects.toMatchObject({code:'evidence_required'});expect((await s.completeRecommendation(restaurantId,recommendation.id,'POS report reviewed.')).status).toBe('completed')});
});
