import{describe,expect,it}from'vitest';import type{Actor}from'../src/domain/types';import{PlatformService,resolveHierarchyPolicy}from'../src/platform/service';import{MemoryPlatformStore}from'../src/platform/store';
const actor:Actor={id:'11111111-1111-4111-8111-111111111111',platformRole:'admin'},org='22222222-2222-4222-8222-222222222222',agency='33333333-3333-4333-8333-333333333333';
async function signature(secret:string,body:string){const e=new TextEncoder(),key=await crypto.subtle.importKey('raw',e.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),s=await crypto.subtle.sign('HMAC',key,e.encode(body));return[...new Uint8Array(s)].map(v=>v.toString(16).padStart(2,'0')).join('')}
function setup(){return new PlatformService(new MemoryPlatformStore(),{enabled:true,billingWebhooksEnabled:true,billingSecret:'a-secret-long-enough-for-tests'})}
describe('Phase 9 expansion platform',()=>{
it('resolves hierarchy with the strictest safety policy winning',()=>{const resolved=resolveHierarchyPolicy([{source:'organization',safetyLevel:1,settings:{tone:'warm',auto:true}},{source:'brand',safetyLevel:2,settings:{tone:'formal'}},{source:'restaurant',safetyLevel:5,settings:{auto:false}}]);expect(resolved.auto).toBe(false);expect(resolved.safetyLevel).toBe(5);expect(resolved.tone).toBe('formal')});
it('revokes agency grants immediately',async()=>{const s=setup(),rel=await s.createAgency(actor,agency,org);await s.activateAgency(rel.id);const grant=await s.grant(actor,rel.id,'approve_replies');expect(await s.canDelegate(rel.id,'approve_replies')).toBe(true);await s.revokeAgency(actor,rel.id);expect(await s.canDelegate(rel.id,'approve_replies')).toBe(false);expect((await s.store.listGrants(rel.id)).find(v=>v.id===grant.id)?.active).toBe(false)});
it('enforces entitlements, limits, and idempotent usage',async()=>{const s=setup();await expect(s.recordUsage(org,'reviews',1,'usage-0001')).rejects.toMatchObject({code:'entitlement_required'});await s.entitlement(org,'reviews',true,2,'plan');const first=await s.recordUsage(org,'reviews',1,'usage-0001');expect((await s.recordUsage(org,'reviews',1,'usage-0001')).id).toBe(first.id);await s.recordUsage(org,'reviews',1,'usage-0002');await expect(s.recordUsage(org,'reviews',1,'usage-0003')).rejects.toMatchObject({code:'entitlement_limit'})});
it('verifies billing signatures and ignores webhook replay',async()=>{const s=setup(),body=JSON.stringify({plan:'pro',status:'active',customerId:'cus_1',subscriptionId:'sub_1'}),sig=await signature('a-secret-long-enough-for-tests',body);await expect(s.billingEvent('stripe_adapter','evt_bad','subscription.updated',body,'bad',org)).rejects.toMatchObject({code:'invalid_signature'});const first=await s.billingEvent('stripe_adapter','evt_1','subscription.updated',body,sig,org),second=await s.billingEvent('stripe_adapter','evt_1','subscription.updated',body,sig,org);expect(first.status).toBe('processed');expect(second.id).toBe(first.id);expect((await s.store.getSubscription(org))?.plan).toBe('pro')});
it('requires verified provider evidence and exact bulk previews',async()=>{const s=setup();await expect(s.capability('zomato','read_reviews',true,'unverified','No supported API evidence.')).rejects.toMatchObject({code:'capability_unverified'});const capability=await s.capability('google','read_reviews',true,'verified','Existing controlled integration tests.');expect(capability.supported).toBe(true);const preview=await s.previewBulk(actor,org,'pause_autopilot',['r1','r2'],'bulk-0001',{r2:'No active policy.'});expect(preview.eligibleIds).toEqual(['r1']);await expect(s.executeBulk(org,'wrong','bulk-0001')).rejects.toMatchObject({code:'bulk_preview_required'});expect((await s.executeBulk(org,preview.id,'bulk-0001')).status).toBe('executed')});
});
