import type { Actor } from '../domain/types';
import { AppError } from '../lib/errors';
import { newId } from '../lib/id';
import type { IncidentStore } from './store';
import type { CustomerRecoveryRecord, GroupingSuggestion, IncidentAction, IncidentEvidence, IncidentSignal, IncidentVerification, OperationalIncident } from './types';

export interface IncidentConfig{enabled:boolean;}
export interface IncidentFactory{(env:CloudflareBindings):IncidentService;}

export class IncidentService{
  constructor(readonly store:IncidentStore,readonly config:IncidentConfig){}
  private assertEnabled(){if(!this.config.enabled)throw new AppError('Phase 6 issue-resolution layer is disabled.',503,'incidents_disabled');}
  private async incident(restaurantId:string,id:string){const value=await this.store.getIncident(id);if(!value||value.restaurantId!==restaurantId)throw new AppError('Incident not found.',404,'not_found');return value;}

  async create(actor:Actor,restaurantId:string,input:Omit<OperationalIncident,'id'|'restaurantId'|'status'|'escalationState'|'createdBy'|'createdAt'|'updatedAt'>){
    this.assertEnabled();const now=new Date().toISOString();const incident:OperationalIncident={id:newId(),restaurantId,...input,status:input.severity==='critical'?'contained':'open',escalationState:input.severity==='critical'?'contained':'none',createdBy:actor.id,createdAt:now,updatedAt:now};return this.store.createIncident(incident);
  }
  async addSignal(restaurantId:string,incidentId:string,input:Omit<IncidentSignal,'id'|'restaurantId'|'incidentId'|'groupingStatus'|'createdAt'>,confirmed=false){
    this.assertEnabled();await this.incident(restaurantId,incidentId);const value:IncidentSignal={id:newId(),restaurantId,incidentId,...input,groupingStatus:confirmed?'confirmed':'suggested',createdAt:new Date().toISOString()};return this.store.addSignal(value);
  }
  async decideSignal(restaurantId:string,signalId:string,decision:'confirmed'|'rejected'){
    this.assertEnabled();const signal=await this.store.getSignal(signalId);if(!signal||signal.restaurantId!==restaurantId)throw new AppError('Incident signal not found.',404,'not_found');if(signal.groupingStatus!=='suggested')throw new AppError('Grouping suggestion was already decided.',409,'invalid_state');return this.store.updateSignal(signalId,{groupingStatus:decision});
  }
  async suggestGrouping(restaurantId:string):Promise<GroupingSuggestion[]>{
    this.assertEnabled();const signals=(await this.store.listRestaurantSignals(restaurantId)).filter(s=>s.groupingStatus!=='rejected');const byCategory=new Map<string,IncidentSignal[]>();for(const signal of signals){const list=byCategory.get(signal.category)??[];list.push(signal);byCategory.set(signal.category,list);}return[...byCategory.entries()].filter(([,list])=>list.length>=2).map(([category,list])=>({category,signalIds:list.map(v=>v.id),confidence:list.length>=4?'high':list.length>=3?'medium':'low',evidence:list.map(v=>v.summary)}));
  }
  async update(restaurantId:string,id:string,patch:Partial<Pick<OperationalIncident,'title'|'category'|'severity'|'confidence'|'ownerId'|'dueAt'|'rootCauseHypothesis'|'confirmedRootCause'|'escalationState'|'status'>>){this.assertEnabled();await this.incident(restaurantId,id);return this.store.updateIncident(id,{...patch,updatedAt:new Date().toISOString()});}
  async addAction(restaurantId:string,incidentId:string,input:Omit<IncidentAction,'id'|'restaurantId'|'incidentId'|'status'|'createdAt'|'completedAt'>){this.assertEnabled();await this.incident(restaurantId,incidentId);return this.store.addAction({id:newId(),restaurantId,incidentId,...input,status:'open',createdAt:new Date().toISOString()});}
  async updateAction(restaurantId:string,actionId:string,patch:Partial<Pick<IncidentAction,'status'|'assigneeId'|'approverId'|'dueAt'|'completionEvidence'>>){this.assertEnabled();const action=await this.store.getAction(actionId);if(!action||action.restaurantId!==restaurantId)throw new AppError('Incident action not found.',404,'not_found');if(patch.status==='completed'&&!patch.completionEvidence&&!action.completionEvidence)throw new AppError('Completion evidence is required.',422,'evidence_required');return this.store.updateAction(actionId,{...patch,...(patch.status==='completed'?{completedAt:new Date().toISOString()}: {})});}
  async addEvidence(actor:Actor,restaurantId:string,incidentId:string,input:Omit<IncidentEvidence,'id'|'restaurantId'|'incidentId'|'createdBy'|'createdAt'>){this.assertEnabled();await this.incident(restaurantId,incidentId);return this.store.addEvidence({id:newId(),restaurantId,incidentId,...input,createdBy:actor.id,createdAt:new Date().toISOString()});}
  async addRecovery(actor:Actor,restaurantId:string,incidentId:string,input:Omit<CustomerRecoveryRecord,'id'|'restaurantId'|'incidentId'|'createdBy'|'createdAt'|'updatedAt'>){this.assertEnabled();const incident=await this.incident(restaurantId,incidentId);if(!incident.restricted)throw new AppError('Customer recovery records require a restricted incident.',409,'restricted_incident_required');if(input.amountMinor&&input.compensationAuthority!=='approved')throw new AppError('Compensation amount requires approved authority.',422,'compensation_not_approved');const now=new Date().toISOString();return this.store.addRecovery({id:newId(),restaurantId,incidentId,...input,createdBy:actor.id,createdAt:now,updatedAt:now});}
  async verify(actor:Actor,restaurantId:string,incidentId:string,result:IncidentVerification['result'],evidence:string){this.assertEnabled();await this.incident(restaurantId,incidentId);const verification=await this.store.addVerification({id:newId(),restaurantId,incidentId,result,evidence,verifiedBy:actor.id,verifiedAt:new Date().toISOString()});await this.store.updateIncident(incidentId,{status:result==='verified_resolved'?'resolved':'action_required',...(result==='verified_resolved'?{closedAt:new Date().toISOString()}:{}),updatedAt:new Date().toISOString()});return verification;}
  async close(restaurantId:string,incidentId:string,mode:'resolved'|'dismissed',reason?:string){
    this.assertEnabled();await this.incident(restaurantId,incidentId);if(mode==='dismissed'){if(!reason?.trim())throw new AppError('Dismissal reason is required.',422,'dismissal_reason_required');return this.store.updateIncident(incidentId,{status:'dismissed',dismissalReason:reason,closedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}
    const verifications=await this.store.listVerifications(incidentId);if(!verifications.some(v=>v.result==='verified_resolved'))throw new AppError('Verified resolution evidence is required.',409,'verification_required');return this.store.updateIncident(incidentId,{status:'resolved',closedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
  }
  async reopen(restaurantId:string,incidentId:string,reason:string){this.assertEnabled();const current=await this.incident(restaurantId,incidentId);if(!['resolved','dismissed'].includes(current.status))throw new AppError('Only closed incidents can be reopened.',409,'invalid_state');await this.store.addEvidence({id:newId(),restaurantId,incidentId,evidenceType:'note',content:`Reopened: ${reason}`,restricted:current.restricted,createdBy:current.createdBy,createdAt:new Date().toISOString()});return this.store.updateIncident(incidentId,{status:'reopened',reopenedAt:new Date().toISOString(),closedAt:undefined,updatedAt:new Date().toISOString()});}
  async detail(restaurantId:string,incidentId:string,includeRestricted:boolean){this.assertEnabled();const incident=await this.incident(restaurantId,incidentId);const [signals,actions,evidence,verifications,recoveries]=await Promise.all([this.store.listSignals(incidentId),this.store.listActions(incidentId),this.store.listEvidence(incidentId),this.store.listVerifications(incidentId),includeRestricted?this.store.listRecoveries(incidentId):Promise.resolve([])]);return{incident,signals,actions,evidence:evidence.filter(v=>includeRestricted||!v.restricted),verifications,recoveries};}
}
