import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { AppError } from '../lib/errors';
import type { CustomerRecoveryRecord, IncidentAction, IncidentEvidence, IncidentSignal, IncidentVerification, OperationalIncident } from './types';

export interface IncidentStore {
  createIncident(value: OperationalIncident): Promise<OperationalIncident>;
  getIncident(id: string): Promise<OperationalIncident | null>;
  updateIncident(id: string, patch: Partial<OperationalIncident>): Promise<OperationalIncident>;
  listIncidents(restaurantId: string): Promise<OperationalIncident[]>;
  addSignal(value: IncidentSignal): Promise<IncidentSignal>;
  getSignal(id: string): Promise<IncidentSignal | null>;
  updateSignal(id: string, patch: Partial<IncidentSignal>): Promise<IncidentSignal>;
  listSignals(incidentId: string): Promise<IncidentSignal[]>;
  listRestaurantSignals(restaurantId: string): Promise<IncidentSignal[]>;
  addAction(value: IncidentAction): Promise<IncidentAction>;
  getAction(id: string): Promise<IncidentAction | null>;
  updateAction(id: string, patch: Partial<IncidentAction>): Promise<IncidentAction>;
  listActions(incidentId: string): Promise<IncidentAction[]>;
  addEvidence(value: IncidentEvidence): Promise<IncidentEvidence>;
  listEvidence(incidentId: string): Promise<IncidentEvidence[]>;
  addRecovery(value: CustomerRecoveryRecord): Promise<CustomerRecoveryRecord>;
  updateRecovery(id: string, patch: Partial<CustomerRecoveryRecord>): Promise<CustomerRecoveryRecord>;
  listRecoveries(incidentId: string): Promise<CustomerRecoveryRecord[]>;
  addVerification(value: IncidentVerification): Promise<IncidentVerification>;
  listVerifications(incidentId: string): Promise<IncidentVerification[]>;
}

function clone<T>(value:T):T{return structuredClone(value);}

export class MemoryIncidentStore implements IncidentStore {
  incidents=new Map<string,OperationalIncident>();signals=new Map<string,IncidentSignal>();actions=new Map<string,IncidentAction>();evidence=new Map<string,IncidentEvidence>();recoveries=new Map<string,CustomerRecoveryRecord>();verifications=new Map<string,IncidentVerification>();
  async createIncident(v:OperationalIncident){this.incidents.set(v.id,clone(v));return clone(v);} async getIncident(id:string){return clone(this.incidents.get(id)??null);} async updateIncident(id:string,p:Partial<OperationalIncident>){const c=this.incidents.get(id);if(!c)throw new AppError('Incident not found.',404,'not_found');const v={...c,...p};this.incidents.set(id,clone(v));return clone(v);} async listIncidents(r:string){return[...this.incidents.values()].filter(v=>v.restaurantId===r).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(clone);}
  async addSignal(v:IncidentSignal){this.signals.set(v.id,clone(v));return clone(v);} async getSignal(id:string){return clone(this.signals.get(id)??null);} async updateSignal(id:string,p:Partial<IncidentSignal>){const c=this.signals.get(id);if(!c)throw new AppError('Incident signal not found.',404,'not_found');const v={...c,...p};this.signals.set(id,clone(v));return clone(v);} async listSignals(i:string){return[...this.signals.values()].filter(v=>v.incidentId===i).map(clone);} async listRestaurantSignals(r:string){return[...this.signals.values()].filter(v=>v.restaurantId===r).map(clone);}
  async addAction(v:IncidentAction){this.actions.set(v.id,clone(v));return clone(v);} async getAction(id:string){return clone(this.actions.get(id)??null);} async updateAction(id:string,p:Partial<IncidentAction>){const c=this.actions.get(id);if(!c)throw new AppError('Incident action not found.',404,'not_found');const v={...c,...p};this.actions.set(id,clone(v));return clone(v);} async listActions(i:string){return[...this.actions.values()].filter(v=>v.incidentId===i).map(clone);}
  async addEvidence(v:IncidentEvidence){this.evidence.set(v.id,clone(v));return clone(v);} async listEvidence(i:string){return[...this.evidence.values()].filter(v=>v.incidentId===i).map(clone);}
  async addRecovery(v:CustomerRecoveryRecord){this.recoveries.set(v.id,clone(v));return clone(v);} async updateRecovery(id:string,p:Partial<CustomerRecoveryRecord>){const c=this.recoveries.get(id);if(!c)throw new AppError('Recovery record not found.',404,'not_found');const v={...c,...p};this.recoveries.set(id,clone(v));return clone(v);} async listRecoveries(i:string){return[...this.recoveries.values()].filter(v=>v.incidentId===i).map(clone);}
  async addVerification(v:IncidentVerification){this.verifications.set(v.id,clone(v));return clone(v);} async listVerifications(i:string){return[...this.verifications.values()].filter(v=>v.incidentId===i).map(clone);}
}

type Row=Record<string,unknown>;const snake=(v:object):Row=>Object.fromEntries(Object.entries(v).filter(([,x])=>x!==undefined).map(([k,x])=>[k.replace(/[A-Z]/g,l=>`_${l.toLowerCase()}`),x]));const camel=(r:Row):Row=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k.replace(/_([a-z])/g,(_,l:string)=>l.toUpperCase()),v]));
function one<T>(d:T|null,e:{message:string}|null,l:string):T{if(e)throw new AppError(`${l}: ${e.message}`,500,'incident_store_error');if(!d)throw new AppError(`${l} returned no data.`,500,'incident_store_error');return d;}

export class SupabaseIncidentStore implements IncidentStore {
  private client:SupabaseClient;constructor(url:string,key:string){if(!url||!key)throw new AppError('Incident storage is not configured.',503,'incidents_not_configured');this.client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
  async createIncident(v:OperationalIncident){const{data,error}=await this.client.from('operational_incidents').insert(snake(v)).select().single();return camel(one(data,error,'Create incident')) as unknown as OperationalIncident;} async getIncident(id:string){const{data,error}=await this.client.from('operational_incidents').select('*').eq('id',id).maybeSingle();if(error)throw new AppError(error.message,500,'incident_store_error');return data?camel(data) as unknown as OperationalIncident:null;} async updateIncident(id:string,p:Partial<OperationalIncident>){const m={...p}as Row;delete m.id;delete m.restaurantId;const{data,error}=await this.client.from('operational_incidents').update(snake(m)).eq('id',id).select().single();return camel(one(data,error,'Update incident')) as unknown as OperationalIncident;} async listIncidents(r:string){const{data,error}=await this.client.from('operational_incidents').select('*').eq('restaurant_id',r).order('updated_at',{ascending:false});if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as OperationalIncident);}
  async addSignal(v:IncidentSignal){const{data,error}=await this.client.from('incident_signals').insert(snake(v)).select().single();return camel(one(data,error,'Add incident signal'))as unknown as IncidentSignal;} async getSignal(id:string){const{data,error}=await this.client.from('incident_signals').select('*').eq('id',id).maybeSingle();if(error)throw new AppError(error.message,500,'incident_store_error');return data?camel(data)as unknown as IncidentSignal:null;} async updateSignal(id:string,p:Partial<IncidentSignal>){const m={...p}as Row;delete m.id;const{data,error}=await this.client.from('incident_signals').update(snake(m)).eq('id',id).select().single();return camel(one(data,error,'Update incident signal'))as unknown as IncidentSignal;} async listSignals(i:string){const{data,error}=await this.client.from('incident_signals').select('*').eq('incident_id',i).order('created_at');if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as IncidentSignal);} async listRestaurantSignals(r:string){const{data,error}=await this.client.from('incident_signals').select('*').eq('restaurant_id',r).order('created_at',{ascending:false});if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as IncidentSignal);}
  async addAction(v:IncidentAction){const{data,error}=await this.client.from('incident_actions').insert(snake(v)).select().single();return camel(one(data,error,'Add incident action'))as unknown as IncidentAction;} async getAction(id:string){const{data,error}=await this.client.from('incident_actions').select('*').eq('id',id).maybeSingle();if(error)throw new AppError(error.message,500,'incident_store_error');return data?camel(data)as unknown as IncidentAction:null;} async updateAction(id:string,p:Partial<IncidentAction>){const m={...p}as Row;delete m.id;const{data,error}=await this.client.from('incident_actions').update(snake(m)).eq('id',id).select().single();return camel(one(data,error,'Update incident action'))as unknown as IncidentAction;} async listActions(i:string){const{data,error}=await this.client.from('incident_actions').select('*').eq('incident_id',i).order('created_at');if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as IncidentAction);}
  async addEvidence(v:IncidentEvidence){const{data,error}=await this.client.from('incident_evidence').insert(snake(v)).select().single();return camel(one(data,error,'Add incident evidence'))as unknown as IncidentEvidence;} async listEvidence(i:string){const{data,error}=await this.client.from('incident_evidence').select('*').eq('incident_id',i).order('created_at');if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as IncidentEvidence);}
  async addRecovery(v:CustomerRecoveryRecord){const{data,error}=await this.client.from('customer_recovery_records').insert(snake(v)).select().single();return camel(one(data,error,'Add recovery record'))as unknown as CustomerRecoveryRecord;} async updateRecovery(id:string,p:Partial<CustomerRecoveryRecord>){const m={...p}as Row;delete m.id;const{data,error}=await this.client.from('customer_recovery_records').update(snake(m)).eq('id',id).select().single();return camel(one(data,error,'Update recovery'))as unknown as CustomerRecoveryRecord;} async listRecoveries(i:string){const{data,error}=await this.client.from('customer_recovery_records').select('*').eq('incident_id',i).order('created_at');if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as CustomerRecoveryRecord);}
  async addVerification(v:IncidentVerification){const{data,error}=await this.client.from('incident_verifications').insert(snake(v)).select().single();return camel(one(data,error,'Add incident verification'))as unknown as IncidentVerification;} async listVerifications(i:string){const{data,error}=await this.client.from('incident_verifications').select('*').eq('incident_id',i).order('verified_at');if(error)throw new AppError(error.message,500,'incident_store_error');return(data??[]).map(v=>camel(v)as unknown as IncidentVerification);}
}
