export type IncidentSeverity='low'|'medium'|'high'|'critical';
export type IncidentStatus='open'|'investigating'|'action_required'|'verification_pending'|'resolved'|'dismissed'|'reopened'|'contained';

export interface OperationalIncident{ id:string;restaurantId:string;title:string;category:string;severity:IncidentSeverity;confidence:'high'|'medium'|'low';status:IncidentStatus;restricted:boolean;locationId?:string;serviceMode?:string;menuItem?:string;daypart?:string;dateStart?:string;dateEnd?:string;rootCauseHypothesis?:string;confirmedRootCause?:string;ownerId?:string;dueAt?:string;escalationState:'none'|'watch'|'escalated'|'contained';dismissalReason?:string;createdBy:string;createdAt:string;updatedAt:string;closedAt?:string;reopenedAt?:string;}
export interface IncidentSignal{ id:string;restaurantId:string;incidentId:string;signalType:'review'|'listing_finding'|'manual';signalId:string;summary:string;category:string;occurredAt?:string;confidence:'high'|'medium'|'low';groupingStatus:'suggested'|'confirmed'|'rejected';createdAt:string;}
export interface IncidentAction{ id:string;restaurantId:string;incidentId:string;title:string;description:string;assigneeId?:string;approverId?:string;status:'open'|'in_progress'|'completed'|'dismissed';dueAt?:string;dependencies:string[];completionEvidence?:string;createdAt:string;completedAt?:string;}
export interface IncidentEvidence{ id:string;restaurantId:string;incidentId:string;evidenceType:'note'|'screenshot'|'document'|'metric'|'verification';content:string;restricted:boolean;createdBy:string;createdAt:string;}
export interface CustomerRecoveryRecord{ id:string;restaurantId:string;incidentId:string;contactStatus:'not_requested'|'requested'|'completed'|'declined';recoveryType?:string;compensationAuthority:'none'|'approval_required'|'approved';amountMinor?:number;currency?:string;outcome?:string;createdBy:string;createdAt:string;updatedAt:string;}
export interface IncidentVerification{ id:string;restaurantId:string;incidentId:string;result:'verified_resolved'|'failed'|'inconclusive';evidence:string;verifiedBy:string;verifiedAt:string;}
export interface GroupingSuggestion{category:string;signalIds:string[];confidence:'high'|'medium'|'low';evidence:string[];}
