-- Tablevoice Phase 6: issue-resolution layer
create table public.operational_incidents(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,title text not null,category text not null,severity text not null check(severity in('low','medium','high','critical')),confidence text not null check(confidence in('high','medium','low')),status text not null,restricted boolean not null default false,location_id uuid references public.locations(id),service_mode text,menu_item text,daypart text,date_start date,date_end date,root_cause_hypothesis text,confirmed_root_cause text,owner_id uuid references auth.users(id),due_at timestamptz,escalation_state text not null,dismissal_reason text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz,reopened_at timestamptz);
create index incident_queue_idx on public.operational_incidents(restaurant_id,status,severity,updated_at desc);
create table public.incident_signals(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,incident_id uuid not null references public.operational_incidents(id) on delete cascade,signal_type text not null,signal_id text not null,summary text not null,category text not null,occurred_at timestamptz,confidence text not null,grouping_status text not null check(grouping_status in('suggested','confirmed','rejected')),created_at timestamptz not null default now(),unique(incident_id,signal_type,signal_id));
create table public.incident_actions(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,incident_id uuid not null references public.operational_incidents(id) on delete cascade,title text not null,description text not null,assignee_id uuid references auth.users(id),approver_id uuid references auth.users(id),status text not null, due_at timestamptz,dependencies text[] not null default array[]::text[],completion_evidence text,created_at timestamptz not null default now(),completed_at timestamptz);
create table public.incident_evidence(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,incident_id uuid not null references public.operational_incidents(id) on delete cascade,evidence_type text not null,content text not null,restricted boolean not null default false,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.customer_recovery_records(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,incident_id uuid not null references public.operational_incidents(id) on delete cascade,contact_status text not null,recovery_type text,compensation_authority text not null,amount_minor integer,currency text,outcome text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.incident_verifications(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,incident_id uuid not null references public.operational_incidents(id) on delete cascade,result text not null check(result in('verified_resolved','failed','inconclusive')),evidence text not null,verified_by uuid not null references auth.users(id),verified_at timestamptz not null);
alter table public.operational_incidents enable row level security;alter table public.incident_signals enable row level security;alter table public.incident_actions enable row level security;alter table public.incident_evidence enable row level security;alter table public.customer_recovery_records enable row level security;alter table public.incident_verifications enable row level security;
-- Server-only tables; application routes enforce restaurant roles and restricted access.
