-- Tablevoice Phase 7: weekly owner intelligence
create table public.report_metric_snapshots(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,period_start date not null,period_end date not null,metrics jsonb not null,completeness jsonb not null,created_at timestamptz not null default now());
create table public.owner_intelligence_reports(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,period_start date not null,period_end date not null,version integer not null,status text not null check(status in('draft','validated','approved','delivered')),metric_snapshot_id uuid not null references public.report_metric_snapshots(id),headline text not null,wins jsonb not null,risks jsonb not null,pending_decisions jsonb not null,small_sample boolean not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),approved_by uuid references auth.users(id),approved_at timestamptz,unique(restaurant_id,period_start,period_end,version));
create table public.report_recommendations(id uuid primary key default gen_random_uuid(),report_id uuid not null references public.owner_intelligence_reports(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,rank integer not null check(rank between 1 and 3),title text not null,rationale text not null,evidence_ids text[] not null,status text not null,selected_at timestamptz,completed_at timestamptz,completion_evidence text,unique(report_id,rank));
create table public.report_delivery_attempts(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,report_id uuid not null references public.owner_intelligence_reports(id) on delete cascade,channel text not null,destination text,idempotency_key text not null,status text not null,error text,created_at timestamptz not null default now(),completed_at timestamptz,unique(restaurant_id,idempotency_key));
create table public.notification_preferences(restaurant_id uuid not null references public.restaurants(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,email boolean not null default false,whatsapp_link boolean not null default false,in_app boolean not null default true,updated_at timestamptz not null default now(),primary key(restaurant_id,user_id));
create table public.report_feedback(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,report_id uuid not null references public.owner_intelligence_reports(id) on delete cascade,user_id uuid not null references auth.users(id),useful boolean not null,comment text,created_at timestamptz not null default now());
alter table public.report_metric_snapshots enable row level security;alter table public.owner_intelligence_reports enable row level security;alter table public.report_recommendations enable row level security;alter table public.report_delivery_attempts enable row level security;alter table public.notification_preferences enable row level security;alter table public.report_feedback enable row level security;
-- Server-only report tables; application routes enforce restaurant roles and preferences.
