-- Tablevoice Phase 9: hierarchy, agency, entitlements, billing, provider capabilities
create table public.brands(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,status text not null check(status in('active','paused')),created_at timestamptz not null default now());
create table public.location_groups(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,brand_id uuid not null references public.brands(id) on delete cascade,name text not null,parent_group_id uuid references public.location_groups(id),created_at timestamptz not null default now());
create table public.location_assignments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,brand_id uuid not null references public.brands(id) on delete cascade,group_id uuid references public.location_groups(id),restaurant_id uuid not null references public.restaurants(id) on delete cascade,created_at timestamptz not null default now(),unique(organization_id,restaurant_id));
create table public.agency_relationships(id uuid primary key default gen_random_uuid(),agency_organization_id uuid not null references public.organizations(id) on delete cascade,client_organization_id uuid not null references public.organizations(id) on delete cascade,status text not null check(status in('pending','active','revoked')),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),revoked_at timestamptz,check(agency_organization_id<>client_organization_id));
create table public.delegated_grants(id uuid primary key default gen_random_uuid(),relationship_id uuid not null references public.agency_relationships(id) on delete cascade,restaurant_id uuid references public.restaurants(id) on delete cascade,capability text not null,active boolean not null,granted_by uuid not null references auth.users(id),granted_at timestamptz not null,revoked_by uuid references auth.users(id),revoked_at timestamptz);
create table public.entitlements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,key text not null,limit_value integer,enabled boolean not null,source text not null check(source in('plan','override','trial')),effective_at timestamptz not null,expires_at timestamptz,unique(organization_id,key));
create table public.usage_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,restaurant_id uuid references public.restaurants(id),metric text not null,quantity integer not null check(quantity>0),idempotency_key text not null,occurred_at timestamptz not null,created_at timestamptz not null default now(),unique(organization_id,idempotency_key));
create table public.subscription_records(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,provider text not null,external_customer_id text,external_subscription_id text,plan text not null,status text not null,current_period_start timestamptz,current_period_end timestamptz,updated_at timestamptz not null);
create table public.billing_events(id uuid primary key default gen_random_uuid(),provider text not null,external_event_id text not null,type text not null,payload_hash text not null,status text not null,received_at timestamptz not null,processed_at timestamptz,error text,unique(provider,external_event_id));
create table public.provider_capabilities(id uuid primary key default gen_random_uuid(),provider text not null,capability text not null,supported boolean not null,verification_status text not null check(verification_status in('verified','unverified','blocked')),evidence text not null,updated_at timestamptz not null,unique(provider,capability));
create table public.bulk_operation_previews(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,operation text not null,restaurant_ids uuid[] not null,eligible_ids uuid[] not null,blocked jsonb not null,idempotency_key text not null,status text not null check(status in('preview','executed')),created_by uuid not null references auth.users(id),created_at timestamptz not null,executed_at timestamptz,unique(organization_id,idempotency_key));
alter table public.brands enable row level security;alter table public.location_groups enable row level security;alter table public.location_assignments enable row level security;alter table public.agency_relationships enable row level security;alter table public.delegated_grants enable row level security;alter table public.entitlements enable row level security;alter table public.usage_events enable row level security;alter table public.subscription_records enable row level security;alter table public.billing_events enable row level security;alter table public.provider_capabilities enable row level security;alter table public.bulk_operation_previews enable row level security;
-- Expansion tables are server-only. Organization and delegated-capability checks happen in application routes.
